name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is marked as incomplete because it has been open 30 days with no activity. Please remove incomplete label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is marked as incomplete because it has been open 30 days with no activity. Please remove incomplete label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-issue-stale: 30
          days-before-pr-stale: 30
          days-before-issue-close: 5
          days-before-pr-close: 5
          stale-issue-label: 'incomplete'
          stale-pr-label: 'incomplete'
          exempt-issue-labels: 'stalebot/disabled,kind/wishlist'
          exempt-pr-labels: 'stalebot/disabled,state/awaiting-approval'
          remove-stale-when-updated: true